#!/bin/sh

/usr/libexec/xdg-desktop-portal-gtk -r &
logger 'xdg-desktop-portal-gtk started'
sleep 0.5
/usr/libexec/xdg-desktop-portal-wlr -r &
logger 'xdg-desktop-portal-wlr started'
sleep 0.5
/usr/libexec/xdg-desktop-portal -r &
logger 'xdg-desktop-portal started'
sleep 0.5
/usr/libexec/flatpak-portal -r --no-idle-exit &
logger 'flatpak-portal started'
