#!/bin/sh

# gentoo-pipewire-launcher restart &
dinitctl setenv WAYLAND_DISPLAY && dinitctl start kanshi
# kanshi &
fcitx5 -d &
# foot --server &
tmux has-session -t default || tmux new-session -c ~ -d -s default

# wallpaper
swaybg -o "Dell Inc. DELL S2721HN FMDZR83" -m fill -i ~/Pictures/260248-furude-rika-1700x1200.jpg \
       -o "Acer Technologies V226HQL LY7EE006851B" -m fill -i ~/Pictures/260248-furude-rika-1700x1200.jpg &
