#!/bin/fish

dinitctl setenv WAYLAND_DISPLAY && dinitctl start kanshi
fcitx5 -d &
tmux has-session -t default || tmux new-session -c ~ -d -s default

# wallpaper
set -l paper ~/Pictures/wallpapers/bceb37527e12f44f7b48d3dceaaa599a.png
swaybg -o "Dell Inc. DELL S2721HN FMDZR83" -m fill -i $paper \
       -o "Acer Technologies V226HQL LY7EE006851B" -m fill -i $paper &
